# oftcdns configuration file schema
type: map
required: yes
mapping:
  dns:
    type: map
    required: yes
    mapping:
      interface:
        type: str
        required: yes
      port:
        type: int
        required: yes
      zone:
        type: str
        required: yes
      ttl:
        type: int
        required: yes
      count:
        type: int
        required: yes
      services:
        type: seq
        required: yes
        sequence:
        - type: str
          required: yes
      regions:
        type: seq
        required: yes
        sequence:
        - type: str
          required: yes
      default region:
        type: str
        required: yes
      region database:
        type: str
        required: yes
      nodes:
        type: seq
        required: yes
        sequence:
        - type: map
          required: yes
          mapping:
            name:
              type: str
              required: yes
            nickname:
              type: str
              required: no
            limit:
              type: int
              required: no
            records:
              type: seq
              required: yes
              sequence:
              - type: seq
                required: yes
                sequence:
                - type: str
                  required: yes
  irc:
    type: map
    required: yes
    mapping:
      ssl:
        type: bool
        required: yes
      server:
        type: str
        required: yes
      port:
        type: int
        required: yes
      oper:
        type: map
        required: no
        mapping:
          username:
            type: str
            required: yes
          password:
            type: str
            required: yes
      nickname:
        type: str
        required: yes
      realname:
        type: str
        required: yes
      channel:
        type: str
        required: yes
      update period:
        type: int
        required: yes
# vim: set ts=2 sw=2 et:
